CREATE TABLE `payment_authorizations` (
	`id` int AUTO_INCREMENT NOT NULL,
	`referenceNumber` varchar(32) NOT NULL,
	`fullLegalName` varchar(256) NOT NULL,
	`email` varchar(320) NOT NULL,
	`phone` varchar(32) NOT NULL,
	`billingStreet` varchar(256) NOT NULL,
	`billingCity` varchar(128) NOT NULL,
	`billingState` varchar(64) NOT NULL,
	`billingZip` varchar(16) NOT NULL,
	`driversLicense` varchar(64) NOT NULL,
	`vehicleYear` varchar(8) NOT NULL,
	`vehicleMake` varchar(64) NOT NULL,
	`vehicleModel` varchar(64) NOT NULL,
	`vin` varchar(32),
	`licensePlate` varchar(16),
	`mileage` varchar(16),
	`serviceLocation` enum('Fort Lauderdale','Wilton Manors') NOT NULL,
	`invoiceNumber` varchar(64) NOT NULL,
	`serviceDescription` text NOT NULL,
	`authorizedAmount` varchar(32) NOT NULL,
	`paymentMethod` enum('Credit Card','Debit Card','Other') NOT NULL,
	`authorizationDate` varchar(32) NOT NULL,
	`signatureImage` text NOT NULL,
	`signatureName` varchar(256) NOT NULL,
	`agreedToTerms` int NOT NULL DEFAULT 0,
	`confirmedCardholder` int NOT NULL DEFAULT 0,
	`agreedToEmailCopy` int NOT NULL DEFAULT 0,
	`signedAt` varchar(32) NOT NULL,
	`submissionIp` varchar(64),
	`userAgent` text,
	`pdfUrl` text,
	`usedInDispute` int NOT NULL DEFAULT 0,
	`disputeNotes` text,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `payment_authorizations_id` PRIMARY KEY(`id`),
	CONSTRAINT `payment_authorizations_referenceNumber_unique` UNIQUE(`referenceNumber`)
);
